package animation.resource;

import java.util.ListResourceBundle;

public class ChineseEditorResourceBundle extends ListResourceBundle {
	private static final Object[][] contents = {
			{ "version", "0.0.0" },
			{ "build_Date", "Build 1,2009.7" },
			{ "openFile_Icon", "/animation/resource/icon/actions/menu-open.png" },
			{ "saveFile_Icon",
					"/animation/resource/icon/actions/menu-saveall.png" },
			{ "help_Icon", "/animation/resource/icon/actions/help.png" },
			{ "about_Icon", "/animation/resource/icon/icon.png" },
			{ "application_Icon", "/animation/resource/icon/icon.png" },
			{ "applicationTitle", "Animation Editor" },
			{ "okButton_Text", "确定" },
			{ "cancelButton_Text", "取消" },
			{ "fileMenu_Text", "文件" },
			{ "exitMenu_Text", "退出" },
			{ "helpMenu_Text", "帮助" },
			{ "aboutMenu_Text", "关于" },
			{ "newFileMenu_Text", "新建文件" },
			{ "openFileMenu_Text", "打开文件" },
			{ "saveFileMenu_Text", "保存文件" },
			{ "saveAsFileMenu_Text", "另存为..." },
			{ "helpMenuText", "帮助" },
			{ "editMenu_Text", "编辑" },
			{ "undoEditMenu_Text", "Undo" },
			{ "redoEditMenu_Text", "Redo" },
			{ "settingEditMenu_Text", "设置 ..." },
			{ "scaleEditMenu_Text", "缩放全部 ..." },
			{ "UnusedModuleEditMenu_Text", "没用到的 Module" },
			{ "UnusedFrameEditMenu_Text", "没用到的 Frame" },
			{ "layoutMenu_Text", "布局" },
			{ "defaultLayoutMenu_Text", "默认布局" },
			{ "moduleLayoutMenu_Text", "Module布局" },
			{ "spriteLayoutMenu_Text", "Sprite布局" },
			{ "frameLayoutMenu_Text", "Frame布局" },
			{ "actionLayoutMenu_Text", "Action布局" },
			{ "dragButton_ToolTip", "拖动Module" },
			{ "moveModuleButton_ToolTip", "移动Module" },
			{ "moveImageButton_ToolTip", "移动图像" },
			{ "pencilButton_ToolTip", "画笔" },
			{ "zoomButton_ToolTip", "缩放" },
			{ "expandImageButton_ToolTip", "扩展图像" },
			{ "collapseImageButton_ToolTip", "收缩图像" },
			{ "selectImageButton_ToolTip", "选择图像" },
			{ "modulesMapButton_ToolTip", "Module映射" },
			{ "selectTemplate_ToolTip", "选择模板" },
			{ "reflushButton_ToolTip", "刷新" },
			{ "addNewButton_ToolTip", "新增" },
			{ "moveUpButton_ToolTip", "上移" },
			{ "moveDownButton_ToolTip", "下移" },
			{ "removeButton_ToolTip", "删除" },
			{ "stopButton_ToolTip", "停止" },
			{ "stepButton_ToolTip", "下一帧" },
			{ "playButton_ToolTip", "播放" },
			{ "cloneButton_ToolTip", "克隆" },
			{ "flipXButton_ToolTip", "X翻转" },
			{ "flipYButton_ToolTip", "Y翻转" },
			{ "rotateButton_ToolTip", "旋转90度" },
			{ "editBoxButton_ToolTip", "编辑 AttackBox & CollisionBox" },
			{ "gridButton_ToolTip", "显示网格线" },
			{ "showBoxButton_ToolTip", "显示Box" },
			{ "allCheckBox_Text", "全选" },
			{ "speedXCheckBox_Text", "X 速度" },
			{ "speedYCheckBox_Text", "Y 速度" },
			{ "accelerationXCheckBox_Text", "X 加速度" },
			{ "accelerationYCheckBox_Text", "Y 加速度" },
			{ "settingDialog_Title", "选项" },
			{ "tick_Label", "Tick: " },
			{ "attackBoxColor_Label", "AttackBox颜色: " },
			{ "collisionBoxColor_Label", "CollisionBox颜色: " },
			{ "gridColor_Label", "栅格颜色: " },
			{ "axisColor_Label", "坐标轴颜色: " },
			{ "backgroundColorLabel", "背景颜色: " },
			{ "gridSizeLabel", "栅格大小: " },
			{ "selectedBorderColor_Label", "选择边框颜色: " },
			{ "moduleBorderColor_Label", "Module边框颜色: " },
			{ "newFileMenu_Icon",
					"/animation/resource/icon/actions/newFolder.png" },
			{ "openFileMenu_Icon",
					"/animation/resource/icon/actions/menu-open.png" },
			{ "saveFileMenu_Icon",
					"/animation/resource/icon/actions/menu-saveall.png" },
			{ "settingEditMenu_Icon",
					"/animation/resource/icon/vcs/customizeView.png" },
			{ "undoEditMenu_Icon", "/animation/resource/icon/actions/undo.png" },
			{ "redoEditMenu_Icon", "/animation/resource/icon/actions/redo.png" },
			{ "aboutHelpMenu_Icon", "/animation/resource/icon/actions/help.png" },
			{ "copyButton_Icon",
					"/animation/resource/icon/actions/menu-copy.png" },
			{ "pasteButton_Icon",
					"/animation/resource/icon/actions/menu-paste.png" },
			{ "reflushButton_Icon",
					"/animation/resource/icon/runConfigurations/loadingTree.png" },
			{ "addNewButton_Icon", "/animation/resource/icon/general/add.png" },
			{ "cloneButton_Icon", "/animation/resource/icon/actions/export.png" },
			{ "moveUpButton_Icon", "/animation/resource/icon/moveUp.png" },
			{ "moveDownButton_Icon", "/animation/resource/icon/moveDown.png" },
			{ "removeButton_Icon", "/animation/resource/icon/actions/gc.png" },
			{ "dragButton_Icon", "/animation/resource/icon/drag.jpg" },
			{ "moveModuleButton_Icon", "/animation/resource/icon/arrow.png" },
			{ "moveImageButton_Icon",
					"/animation/resource/icon/actions/get.png" },
			{ "zoomButton_Icon", "/animation/resource/icon/actions/replace.png" },
			{ "flipXButton_Icon", "/animation/resource/icon/diff/Diff.png" },
			{ "flipYButton_Icon",
					"/animation/resource/icon/diff/applyNotConflicts.png" },
			{ "rotateButton_Icon",
					"/animation/resource/icon/actions/rollback.png" },
			{ "expandImageButton_Icon",
					"/animation/resource/icon/actions/expandall.png" },
			{ "collapseImageButton_Icon",
					"/animation/resource/icon/actions/collapseall.png" },
			{ "pencilButton_Icon", "/animation/resource/icon/pencil.gif" },
			{ "eraserButton_Icon", "/animation/resource/icon/eraser.gif" },
			{ "playButton_Icon", "/animation/resource/icon/actions/execute.png" },
			{ "pauseButton_Icon", "/animation/resource/icon/actions/pause.png" },
			{ "stepButton_Icon",
					"/animation/resource/icon/actions/refreshUsages.png" },
			{ "stopButton_Icon", "/animation/resource/icon/actions/suspend.png" },
			{ "editBoxButton_Icon", "/animation/resource/icon/attbox.gif" },
			{ "gridButton_Icon", "/animation/resource/icon/grid.gif" },
			{ "showBoxButton_Icon",
					"/animation/resource/icon/runConfigurations/trackTests.png" },
			{ "selectImageButton_Icon",
					"/animation/resource/icon/modules/sourceRootOpened.png" },
			{ "modulesMapButton_Icon",
					"/animation/resource/icon/modules/order.png" } };

	@Override
	protected Object[][] getContents() {
		return contents;
	}
}
