package animation.resource;

import java.util.ListResourceBundle;

public class EnglishEditorResourceBundle extends ListResourceBundle {
	private static final Object[][] contents = {
			{ "version", "0.0.0" },
			{ "build_Date", "Build 1,2009.7" },
			{ "openFile_Icon", "/animation/resource/icon/actions/menu-open.png" },
			{ "saveFile_Icon",
					"/animation/resource/icon/actions/menu-saveall.png" },
			{ "help_Icon", "/animation/resource/icon/actions/help.png" },
			{ "about_Icon", "/animation/resource/icon/icon.png" },
			{ "application_Icon", "/animation/resource/icon/icon.png" },
			{ "applicationTitle", "Animation Editor" },
			{ "okButton_Text", "OK" },
			{ "cancelButton_Text", "Cancel" },
			{ "fileMenu_Text", "File" },
			{ "exitMenu_Text", "Exit" },
			{ "helpMenu_Text", "Help" },
			{ "aboutMenu_Text", "About" },
			{ "newFileMenu_Text", "New File" },
			{ "openFileMenu_Text", "Open File" },
			{ "saveFileMenu_Text", "Save File" },
			{ "saveAsFileMenu_Text", "Save As..." },
			{ "helpMenuText", "Help" },
			{ "editMenu_Text", "Edit" },
			{ "undoEditMenu_Text", "Undo" },
			{ "redoEditMenu_Text", "Redo" },
			{ "settingEditMenu_Text", "Setting ..." },
			{ "scaleEditMenu_Text", "Scale All ..." },
			{ "UnusedModuleEditMenu_Text", "Unused Module" },
			{ "UnusedFrameEditMenu_Text", "Unused Frame" },
			{ "layoutMenu_Text", "Layout" },
			{ "defaultLayoutMenu_Text", "Default Layout" },
			{ "moduleLayoutMenu_Text", "Module Layout" },
			{ "spriteLayoutMenu_Text", "Sprite Layout" },
			{ "frameLayoutMenu_Text", "Frame Layout" },
			{ "actionLayoutMenu_Text", "Action Layout" },
			{ "dragButton_ToolTip", "Drag Module" },
			{ "moveModuleButton_ToolTip", "Move Module" },
			{ "moveImageButton_ToolTip", "Move Image" },
			{ "pencilButton_ToolTip", "Paint Tool" },
			{ "zoomButton_ToolTip", "Zoom" },
			{ "expandImageButton_ToolTip", "Expand Image" },
			{ "collapseImageButton_ToolTip", "Collapse Image" },
			{ "selectImageButton_ToolTip", "Select Image" },
			{ "modulesMapButton_ToolTip", "Modules Mapping" },
			{ "selectTemplate_ToolTip", "Select Template" },
			{ "reflushButton_ToolTip", "refresh" },
			{ "addNewButton_ToolTip", "Add New" },
			{ "moveUpButton_ToolTip", "Move Up" },
			{ "moveDownButton_ToolTip", "Move Down" },
			{ "removeButton_ToolTip", "Remove" },
			{ "stopButton_ToolTip", "Stop" },
			{ "stepButton_ToolTip", "Next Frame" },
			{ "playButton_ToolTip", "Play" },
			{ "cloneButton_ToolTip", "Clone" },
			{ "flipXButton_ToolTip", "FlipX" },
			{ "flipYButton_ToolTip", "FilpY" },
			{ "rotateButton_ToolTip", "Rotate" },
			{ "editBoxButton_ToolTip", "Edit AttackBox & CollisionBox" },
			{ "gridButton_ToolTip", "Show Grid" },
			{ "showBoxButton_ToolTip", "Show AttackBox & CollisionBox" },
			{ "allCheckBox_Text", "All" },
			{ "speedXCheckBox_Text", "Speed X" },
			{ "speedYCheckBox_Text", "Speed Y" },
			{ "accelerationXCheckBox_Text", "Acceleration X" },
			{ "accelerationYCheckBox_Text", "Acceleration Y" },
			{ "settingDialog_Title", "Setting" },
			{ "tick_Label", "Tick: " },
			{ "attackBoxColor_Label", "AttackBox Color: " },
			{ "collisionBoxColor_Label", "CollisionBox Color: " },
			{ "gridColor_Label", "Grid Color: " },
			{ "axisColor_Label", "Axis Color: " },
			{ "backgroundColorLabel", "Background Color: " },
			{ "gridSizeLabel", "Grid Size: " },
			{ "selectedBorderColor_Label", "Selected Border Color: " },
			{ "moduleBorderColor_Label", "Module Border Color: " },
			{ "newFileMenu_Icon",
					"/animation/resource/icon/actions/newFolder.png" },
			{ "openFileMenu_Icon",
					"/animation/resource/icon/actions/menu-open.png" },
			{ "saveFileMenu_Icon",
					"/animation/resource/icon/actions/menu-saveall.png" },
			{ "settingEditMenu_Icon",
					"/animation/resource/icon/vcs/customizeView.png" },
			{ "undoEditMenu_Icon", "/animation/resource/icon/actions/undo.png" },
			{ "redoEditMenu_Icon", "/animation/resource/icon/actions/redo.png" },
			{ "aboutHelpMenu_Icon", "/animation/resource/icon/actions/help.png" },
			{ "copyButton_Icon",
					"/animation/resource/icon/actions/menu-copy.png" },
			{ "pasteButton_Icon",
					"/animation/resource/icon/actions/menu-paste.png" },
			{ "reflushButton_Icon",
					"/animation/resource/icon/runConfigurations/loadingTree.png" },
			{ "addNewButton_Icon", "/animation/resource/icon/general/add.png" },
			{ "cloneButton_Icon", "/animation/resource/icon/actions/export.png" },
			{ "moveUpButton_Icon", "/animation/resource/icon/moveUp.png" },
			{ "moveDownButton_Icon", "/animation/resource/icon/moveDown.png" },
			{ "removeButton_Icon", "/animation/resource/icon/actions/gc.png" },
			{ "dragButton_Icon", "/animation/resource/icon/drag.jpg" },
			{ "moveModuleButton_Icon", "/animation/resource/icon/arrow.png" },
			{ "moveImageButton_Icon",
					"/animation/resource/icon/actions/get.png" },
			{ "zoomButton_Icon", "/animation/resource/icon/actions/replace.png" },
			{ "flipXButton_Icon", "/animation/resource/icon/diff/Diff.png" },
			{ "flipYButton_Icon",
					"/animation/resource/icon/diff/applyNotConflicts.png" },
			{ "rotateButton_Icon",
					"/animation/resource/icon/actions/rollback.png" },
			{ "expandImageButton_Icon",
					"/animation/resource/icon/actions/expandall.png" },
			{ "collapseImageButton_Icon",
					"/animation/resource/icon/actions/collapseall.png" },
			{ "pencilButton_Icon", "/animation/resource/icon/pencil.gif" },
			{ "eraserButton_Icon", "/animation/resource/icon/eraser.gif" },
			{ "playButton_Icon", "/animation/resource/icon/actions/execute.png" },
			{ "pauseButton_Icon", "/animation/resource/icon/actions/pause.png" },
			{ "stepButton_Icon",
					"/animation/resource/icon/actions/refreshUsages.png" },
			{ "stopButton_Icon", "/animation/resource/icon/actions/suspend.png" },
			{ "editBoxButton_Icon", "/animation/resource/icon/attbox.gif" },
			{ "gridButton_Icon", "/animation/resource/icon/grid.gif" },
			{ "showBoxButton_Icon",
					"/animation/resource/icon/runConfigurations/trackTests.png" },
			{ "selectImageButton_Icon",
					"/animation/resource/icon/modules/sourceRootOpened.png" },
			{ "modulesMapButton_Icon",
					"/animation/resource/icon/modules/order.png" } };

	@Override
	protected Object[][] getContents() {
		return contents;
	}
}
